version: "2"
services:
  ravenous-web-ui:
    image: "peterlili/ravenous-web-ui"
    user: "node"
    environment:
      - NODE_ENV=production
      - postgres
    volumes:
      - ./:/home/node/app
    ports:
      - "5000:5000"
    command: "npm start"
  ravenous-postgres:
    image: "alpine:3.10"
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9091:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.10.3.49
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.10.3.49
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.10.3.49
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: 10.10.3.49
  #     KAFKA_ZOOKEEPER_CONNECT: ravenous-zookeeper:2181
      # KAFKA_CREATE_TOPICS: "Topic1:2:1,Topic2:1:1:compact"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  # ravenous-kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: localhost
  #     KAFKA_CREATE_TOPICS: "stream-in:2:1,stream-out:2:1"
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_ZOOKEEPER_CONNECT: ravenous-zookeeper:2181
  #   depends_on:
  #     - ravenous-zookeeper
    # container_name: kafka1
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  # ravenous-kafka2:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9093:9092"
  #   environment:
  #     # KAFKA_ADVERTISED_HOST_NAME: ${ipconfig getifaddr en0}
  #     KAFKA_ADVERTISED_HOST_NAME: 10.10.3.49
  #     KAFKA_CREATE_TOPICS: "stream-in:2:1,stream-out:2:1"
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_ZOOKEEPER_CONNECT: ravenous-zookeeper1:2181
  #   # causing alive broker = 0
  #   depends_on:
  #     - ravenous-zookeeper1
  #   container_name: kafka2
  #   # volumes:
  #   #   - /var/run/docker.sock:/var/run/docker.sock