export const UPDATE_SEARCH_PARAMS = "UPDATE_SEARCH_PARAMS";
export const BUSINESSES_RECEIVED = "BUSINESSES_RECEIVED";
export const SEARCH_PARAMS_FROM_KAFKA = "SEARCH_PARAMS_FROM_KAFKA";
export const UPDATE_TIMES = "UPDATE_TIMES";